spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 91417298428-gu8072er25ognutdlffu5ja7kvvcd6b6.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
